title:
  en: Knitting Our Internet
  it: La Nostra Rete
  de: Unser Netz knüpfen
  tr: İnternetimizi Örgülemek
  el: Πλέκοντας τον Παγκόσμιο Ιστό
author:
  name: Tommi
  website: https://tommi.space/
  email: surfing@tommi.space
url: https://ournet.rocks
image: /ournet.png
source: https://codeberg.org/tommi/ournet
changelog: https://codeberg.org/tommi/ournet/commits/branch/main
issues: https://github.com/xplosionmind/ournet/issues
roadmap: https://github.com/users/xplosionmind/projects/3
translation: https://translate.codeberg.org/projects/ournet/
