title:
  en: Knitting Our Internet
  it: La Nostra Rete
author:
  name: Tommi
  website: https://tommi.space/
  email: surfing@tommi.space
url: https://ournet.rocks
image: https://tommi.space/fedilab-scambi.webp
source: https://codeberg.org/tommi/ournet
changelog: https://codeberg.org/tommi/ournet/commits/branch/main
issues: https://github.com/xplosionmind/ournet/issues
roadmap: https://github.com/users/xplosionmind/projects/3
nav:
  - name:
      en: 🏠 Home
      it: 🏠 Intro
    title:
      en: Go to the homepage
      it: Vai alla homepage
    url:
      en: /
      it: /it/

  - name:
      en: 🌟 Invite
      it: 🌟 Invita
    title:
      en: Info for inviting Tommi to host this workshop
      it: Info per invitare Tommi a tenere questo lab
    url:
      en: /invite/
      it: /invita/

  - name:
      en: 🪡 Weaver kit
      it: 🪡 Weaver kit
    title:
      en: A kit to host the workshop yourself!
      it: Un kit per tenere il workshop tu stessə!
    url:
      en: /knit/
      it: /it/weaver-kit/

#  - name:
#      en: 🛣️ Roadmap
#    title:
#      en: This project’s roadmap
#    url:
#      en: https://github.com/users/xplosionmind/projects/3
