title: Knitting Our Internet
url: https://ournet.rocks
description:
  oneline: A **face-to-face** **participatory** **workshop** about the Internet, its history, and its **future**.
  short: <cite>Knitting Our Internet</cite> is a **face-to-face** **workshop** about the Internet. It consists of an **interactive journey** through its history and a **collective rethinking** of its future.
  full: |
    <cite>Knitting Our Internet</cite> is a **face-to-face** **workshop** about the Internet. It consists of an **interactive journey** through its history and a **collective rethinking** of its future.

    The lab provides tangible examples on how the internet *actually* works, **questioning** the very essence of today’s mainstream social networks. Its main purpose is to expose the critical limits of **surveillance capitalism**, **centralization**, and its **environmental impact**.

    After aknowledging the challenges the digital domain is currently facing, participants are encouraged to reinterpret social networks starting from **decentralization**, envisioning more human, collective, and participatory **digital futures**.
lang: en
image: https://tommi.space/fedilab-scambi.webp
source: https://codeberg.org/tommi/ournet
changelog: https://codeberg.org/tommi/ournet/commits/branch/main
issues: https://github.com/xplosionmind/ournet/issues
roadmap: https://github.com/users/xplosionmind/projects/3
